# Generated by Django 3.0.8 on 2020-08-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportapp', '0003_auto_20200811_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
